#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Glider_SpaceShuttleB

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "B_EmptyBaseGlider_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Glider_SpaceShuttleB.B_Glider_SpaceShuttleB_C
// 0x0018 (0x0380 - 0x0368)
class AB_Glider_SpaceShuttleB_C final : public AB_EmptyBaseGlider_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0368(0x0008)(Transient, DuplicateTransient)
	class UParticleSystemComponent*               IdleEffect;                                        // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             ThrustStartSound;                                  // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_Glider_SpaceShuttleB(int32 EntryPoint);
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void OnParachuteTrailUpdated(float MovementLengthSquared, float ForwardDot, float RightDot, float RotationalMovementAcceleration);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Glider_SpaceShuttleB_C">();
	}
	static class AB_Glider_SpaceShuttleB_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Glider_SpaceShuttleB_C>();
	}
};
static_assert(alignof(AB_Glider_SpaceShuttleB_C) == 0x000008, "Wrong alignment on AB_Glider_SpaceShuttleB_C");
static_assert(sizeof(AB_Glider_SpaceShuttleB_C) == 0x000380, "Wrong size on AB_Glider_SpaceShuttleB_C");
static_assert(offsetof(AB_Glider_SpaceShuttleB_C, UberGraphFrame) == 0x000368, "Member 'AB_Glider_SpaceShuttleB_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AB_Glider_SpaceShuttleB_C, IdleEffect) == 0x000370, "Member 'AB_Glider_SpaceShuttleB_C::IdleEffect' has a wrong offset!");
static_assert(offsetof(AB_Glider_SpaceShuttleB_C, ThrustStartSound) == 0x000378, "Member 'AB_Glider_SpaceShuttleB_C::ThrustStartSound' has a wrong offset!");

}

