#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BluGlo_Node

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BluGlo_Node.BluGlo_Node_C
// 0x00E0 (0x0ED8 - 0x0DF8)
class ABluGlo_Node_C final : public ABuildingProp
{
public:
	uint8                                         Pad_DF8[0x8];                                      // 0x0DF8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0E00(0x0008)(Transient, DuplicateTransient)
	class UPointLightComponent*                   bluLight;                                          // 0x0E08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               IdleParticles;                                     // 0x0E10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   bluglomesh;                                        // 0x0E18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Fort_BluGlo_loop_AudioComponent;                   // 0x0E20(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortMiniMapComponent*                  FortMiniMap;                                       // 0x0E28(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               BluGloSpawnparticle;                               // 0x0E30(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Trail_HorizontalMovement_EEEFB2FD467DE31D5FDEDEA006F5C10F; // 0x0E38(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Trail_VerticalMovement_EEEFB2FD467DE31D5FDEDEA006F5C10F; // 0x0E3C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Trail__Direction_EEEFB2FD467DE31D5FDEDEA006F5C10F; // 0x0E40(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E41[0x7];                                      // 0x0E41(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Trail;                                             // 0x0E48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ActivateEffects;                                   // 0x0E50(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	bool                                          DeActivateEffects;                                 // 0x0E51(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	bool                                          CanInteract;                                       // 0x0E52(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	uint8                                         Pad_E53[0x5];                                      // 0x0E53(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   BluGloQuantity;                                    // 0x0E58(0x0018)(Edit, BlueprintVisible, Net, DisableEditOnInstance)
	class AFortPawn*                              NewVar;                                            // 0x0E70(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                StartLocation;                                     // 0x0E78(0x000C)(Edit, BlueprintVisible, Net, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E84[0x4];                                      // 0x0E84(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               TrailEffect;                                       // 0x0E88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Sound_BluGloLoop;                                  // 0x0E90(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               RandomSpawnRotation;                               // 0x0E98(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_EA4[0x4];                                      // 0x0EA4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABluGlow_MorphAnimation_C*              BlugloRef;                                         // 0x0EA8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UForceFeedbackEffect*                   PickupForceFeedback;                               // 0x0EB0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortWorldItemDefinition*               BlugloItemDef;                                     // 0x0EB8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CollectText;                                       // 0x0EC0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_BluGlo_Node(int32 EntryPoint);
	void ShowSpawnTrail(const struct FVector& StartLocation_0, float AnimDelay);
	void HandleMissionEvent_LocateBluGlo(const struct FGuid& InMissionGuid, const struct FGameplayTagContainer& ObjectiveHandle, class UFortMissionEventParams* Params_0, bool DO_NOT_USE_THIS_OR_VARIABLES_BELOW, class UObject* EventFocus, const class UDataAsset* EventContent, class AActor* EventInstigator, int32 GenericInt, float GenericFloat, const class FText& GenericText, const struct FGameplayTagContainer& GameplayTags, const struct FFortMissionEvent& MissionEvent);
	void BlueprintOnInteract(const class AFortPawn* InteractingPawn);
	void ReceiveBeginPlay();
	void Trail__UpdateFunc();
	void Trail__FinishedFunc();
	void UserConstructionScript();
	void OnRep_ActivateEffects();
	void OnRep_DeActivateEffects();
	void OnRep_CanInteract();

	bool BlueprintCanInteract(const class AFortPawn* InteractingPawn) const;
	class FText BlueprintGetInteractionString(const class AFortPawn* InteractingPawn) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BluGlo_Node_C">();
	}
	static class ABluGlo_Node_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABluGlo_Node_C>();
	}
};
static_assert(alignof(ABluGlo_Node_C) == 0x000008, "Wrong alignment on ABluGlo_Node_C");
static_assert(sizeof(ABluGlo_Node_C) == 0x000ED8, "Wrong size on ABluGlo_Node_C");
static_assert(offsetof(ABluGlo_Node_C, UberGraphFrame) == 0x000E00, "Member 'ABluGlo_Node_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, bluLight) == 0x000E08, "Member 'ABluGlo_Node_C::bluLight' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, IdleParticles) == 0x000E10, "Member 'ABluGlo_Node_C::IdleParticles' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, bluglomesh) == 0x000E18, "Member 'ABluGlo_Node_C::bluglomesh' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, Fort_BluGlo_loop_AudioComponent) == 0x000E20, "Member 'ABluGlo_Node_C::Fort_BluGlo_loop_AudioComponent' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, FortMiniMap) == 0x000E28, "Member 'ABluGlo_Node_C::FortMiniMap' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, BluGloSpawnparticle) == 0x000E30, "Member 'ABluGlo_Node_C::BluGloSpawnparticle' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, Trail_HorizontalMovement_EEEFB2FD467DE31D5FDEDEA006F5C10F) == 0x000E38, "Member 'ABluGlo_Node_C::Trail_HorizontalMovement_EEEFB2FD467DE31D5FDEDEA006F5C10F' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, Trail_VerticalMovement_EEEFB2FD467DE31D5FDEDEA006F5C10F) == 0x000E3C, "Member 'ABluGlo_Node_C::Trail_VerticalMovement_EEEFB2FD467DE31D5FDEDEA006F5C10F' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, Trail__Direction_EEEFB2FD467DE31D5FDEDEA006F5C10F) == 0x000E40, "Member 'ABluGlo_Node_C::Trail__Direction_EEEFB2FD467DE31D5FDEDEA006F5C10F' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, Trail) == 0x000E48, "Member 'ABluGlo_Node_C::Trail' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, ActivateEffects) == 0x000E50, "Member 'ABluGlo_Node_C::ActivateEffects' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, DeActivateEffects) == 0x000E51, "Member 'ABluGlo_Node_C::DeActivateEffects' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, CanInteract) == 0x000E52, "Member 'ABluGlo_Node_C::CanInteract' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, BluGloQuantity) == 0x000E58, "Member 'ABluGlo_Node_C::BluGloQuantity' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, NewVar) == 0x000E70, "Member 'ABluGlo_Node_C::NewVar' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, StartLocation) == 0x000E78, "Member 'ABluGlo_Node_C::StartLocation' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, TrailEffect) == 0x000E88, "Member 'ABluGlo_Node_C::TrailEffect' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, Sound_BluGloLoop) == 0x000E90, "Member 'ABluGlo_Node_C::Sound_BluGloLoop' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, RandomSpawnRotation) == 0x000E98, "Member 'ABluGlo_Node_C::RandomSpawnRotation' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, BlugloRef) == 0x000EA8, "Member 'ABluGlo_Node_C::BlugloRef' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, PickupForceFeedback) == 0x000EB0, "Member 'ABluGlo_Node_C::PickupForceFeedback' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, BlugloItemDef) == 0x000EB8, "Member 'ABluGlo_Node_C::BlugloItemDef' has a wrong offset!");
static_assert(offsetof(ABluGlo_Node_C, CollectText) == 0x000EC0, "Member 'ABluGlo_Node_C::CollectText' has a wrong offset!");

}

