#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Hex_Outpost_Theater2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Hex_PARENT_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Hex_Outpost_Theater2.BP_Hex_Outpost_Theater2_C
// 0x0048 (0x0718 - 0x06D0)
class ABP_Hex_Outpost_Theater2_C final : public ABP_Hex_PARENT_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Hex_Outpost_Theater2_C;          // 0x06D0(0x0008)(Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x06D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Flagpole;                                          // 0x06E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x06E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   FlagLight;                                         // 0x06F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tip;                                               // 0x06F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   MeshCommandCenterFlag;                             // 0x0700(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Outpost_Core;                                   // 0x0708(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               BannerMID;                                         // 0x0710(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Hex_Outpost_Theater2(int32 EntryPoint);
	void ActivateOutpost();
	void HandleOnPlayerInfoChanged(const struct FUniqueNetIdRepl& UniqueId);
	void ReceiveBeginPlay();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Hex_Outpost_Theater2_C">();
	}
	static class ABP_Hex_Outpost_Theater2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Hex_Outpost_Theater2_C>();
	}
};
static_assert(alignof(ABP_Hex_Outpost_Theater2_C) == 0x000008, "Wrong alignment on ABP_Hex_Outpost_Theater2_C");
static_assert(sizeof(ABP_Hex_Outpost_Theater2_C) == 0x000718, "Wrong size on ABP_Hex_Outpost_Theater2_C");
static_assert(offsetof(ABP_Hex_Outpost_Theater2_C, UberGraphFrame_BP_Hex_Outpost_Theater2_C) == 0x0006D0, "Member 'ABP_Hex_Outpost_Theater2_C::UberGraphFrame_BP_Hex_Outpost_Theater2_C' has a wrong offset!");
static_assert(offsetof(ABP_Hex_Outpost_Theater2_C, StaticMesh1) == 0x0006D8, "Member 'ABP_Hex_Outpost_Theater2_C::StaticMesh1' has a wrong offset!");
static_assert(offsetof(ABP_Hex_Outpost_Theater2_C, Flagpole) == 0x0006E0, "Member 'ABP_Hex_Outpost_Theater2_C::Flagpole' has a wrong offset!");
static_assert(offsetof(ABP_Hex_Outpost_Theater2_C, StaticMesh) == 0x0006E8, "Member 'ABP_Hex_Outpost_Theater2_C::StaticMesh' has a wrong offset!");
static_assert(offsetof(ABP_Hex_Outpost_Theater2_C, FlagLight) == 0x0006F0, "Member 'ABP_Hex_Outpost_Theater2_C::FlagLight' has a wrong offset!");
static_assert(offsetof(ABP_Hex_Outpost_Theater2_C, Tip) == 0x0006F8, "Member 'ABP_Hex_Outpost_Theater2_C::Tip' has a wrong offset!");
static_assert(offsetof(ABP_Hex_Outpost_Theater2_C, MeshCommandCenterFlag) == 0x000700, "Member 'ABP_Hex_Outpost_Theater2_C::MeshCommandCenterFlag' has a wrong offset!");
static_assert(offsetof(ABP_Hex_Outpost_Theater2_C, SM_Outpost_Core) == 0x000708, "Member 'ABP_Hex_Outpost_Theater2_C::SM_Outpost_Core' has a wrong offset!");
static_assert(offsetof(ABP_Hex_Outpost_Theater2_C, BannerMID) == 0x000710, "Member 'ABP_Hex_Outpost_Theater2_C::BannerMID' has a wrong offset!");

}

