#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_StarRating_M

#include "Basic.hpp"

#include "ButtonStyle_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-StarRating-M.ButtonStyle-StarRating-M_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonStyle_StarRating_M_C final : public UButtonStyle_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-StarRating-M_C">();
	}
	static class UButtonStyle_StarRating_M_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_StarRating_M_C>();
	}
};
static_assert(alignof(UButtonStyle_StarRating_M_C) == 0x000008, "Wrong alignment on UButtonStyle_StarRating_M_C");
static_assert(sizeof(UButtonStyle_StarRating_M_C) == 0x0004F0, "Wrong size on UButtonStyle_StarRating_M_C");

}

