#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_Minus

#include "Basic.hpp"

#include "ButtonStyle_MediumTransparentNoCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle_Minus.ButtonStyle_Minus_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonStyle_Minus_C final : public UButtonStyle_MediumTransparentNoCues_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle_Minus_C">();
	}
	static class UButtonStyle_Minus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_Minus_C>();
	}
};
static_assert(alignof(UButtonStyle_Minus_C) == 0x000008, "Wrong alignment on UButtonStyle_Minus_C");
static_assert(sizeof(UButtonStyle_Minus_C) == 0x0004F0, "Wrong size on UButtonStyle_Minus_C");

}

