#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CommonInput

#include "Basic.hpp"

#include "CommonInput_structs.hpp"


namespace SDK::Params
{

// Function CommonInput.CommonInputContext.SetCurrentInputType
// 0x0001 (0x0001 - 0x0000)
struct CommonInputContext_SetCurrentInputType final
{
public:
	ECommonInputType                              NewInputType;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(CommonInputContext_SetCurrentInputType) == 0x000001, "Wrong alignment on CommonInputContext_SetCurrentInputType");
static_assert(sizeof(CommonInputContext_SetCurrentInputType) == 0x000001, "Wrong size on CommonInputContext_SetCurrentInputType");
static_assert(offsetof(CommonInputContext_SetCurrentInputType, NewInputType) == 0x000000, "Member 'CommonInputContext_SetCurrentInputType::NewInputType' has a wrong offset!");

// Function CommonInput.CommonInputContext.SetGamepadInputType
// 0x0001 (0x0001 - 0x0000)
struct CommonInputContext_SetGamepadInputType final
{
public:
	ECommonGamepadType                            InGamepadInputType;                                // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(CommonInputContext_SetGamepadInputType) == 0x000001, "Wrong alignment on CommonInputContext_SetGamepadInputType");
static_assert(sizeof(CommonInputContext_SetGamepadInputType) == 0x000001, "Wrong size on CommonInputContext_SetGamepadInputType");
static_assert(offsetof(CommonInputContext_SetGamepadInputType, InGamepadInputType) == 0x000000, "Member 'CommonInputContext_SetGamepadInputType::InGamepadInputType' has a wrong offset!");

// Function CommonInput.CommonInputContext.GetCurrentGamepadType
// 0x0001 (0x0001 - 0x0000)
struct CommonInputContext_GetCurrentGamepadType final
{
public:
	ECommonGamepadType                            ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(CommonInputContext_GetCurrentGamepadType) == 0x000001, "Wrong alignment on CommonInputContext_GetCurrentGamepadType");
static_assert(sizeof(CommonInputContext_GetCurrentGamepadType) == 0x000001, "Wrong size on CommonInputContext_GetCurrentGamepadType");
static_assert(offsetof(CommonInputContext_GetCurrentGamepadType, ReturnValue) == 0x000000, "Member 'CommonInputContext_GetCurrentGamepadType::ReturnValue' has a wrong offset!");

// Function CommonInput.CommonInputContext.GetCurrentInputType
// 0x0001 (0x0001 - 0x0000)
struct CommonInputContext_GetCurrentInputType final
{
public:
	ECommonInputType                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(CommonInputContext_GetCurrentInputType) == 0x000001, "Wrong alignment on CommonInputContext_GetCurrentInputType");
static_assert(sizeof(CommonInputContext_GetCurrentInputType) == 0x000001, "Wrong size on CommonInputContext_GetCurrentInputType");
static_assert(offsetof(CommonInputContext_GetCurrentInputType, ReturnValue) == 0x000000, "Member 'CommonInputContext_GetCurrentInputType::ReturnValue' has a wrong offset!");

// Function CommonInput.CommonInputContext.IsUsingPointerInput
// 0x0001 (0x0001 - 0x0000)
struct CommonInputContext_IsUsingPointerInput final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(CommonInputContext_IsUsingPointerInput) == 0x000001, "Wrong alignment on CommonInputContext_IsUsingPointerInput");
static_assert(sizeof(CommonInputContext_IsUsingPointerInput) == 0x000001, "Wrong size on CommonInputContext_IsUsingPointerInput");
static_assert(offsetof(CommonInputContext_IsUsingPointerInput, ReturnValue) == 0x000000, "Member 'CommonInputContext_IsUsingPointerInput::ReturnValue' has a wrong offset!");

}

