#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_SML_CAU_Sarah_Head_01_Dyn_AnimBP

#include "Basic.hpp"


namespace SDK::Params
{

// Function F_SML_CAU_Sarah_Head_01_Dyn_AnimBP.F_SML_CAU_Sarah_Head_01_Dyn_AnimBP_C.ExecuteUbergraph_F_SML_CAU_Sarah_Head_01_Dyn_AnimBP
// 0x0004 (0x0004 - 0x0000)
struct F_SML_CAU_Sarah_Head_01_Dyn_AnimBP_C_ExecuteUbergraph_F_SML_CAU_Sarah_Head_01_Dyn_AnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(F_SML_CAU_Sarah_Head_01_Dyn_AnimBP_C_ExecuteUbergraph_F_SML_CAU_Sarah_Head_01_Dyn_AnimBP) == 0x000004, "Wrong alignment on F_SML_CAU_Sarah_Head_01_Dyn_AnimBP_C_ExecuteUbergraph_F_SML_CAU_Sarah_Head_01_Dyn_AnimBP");
static_assert(sizeof(F_SML_CAU_Sarah_Head_01_Dyn_AnimBP_C_ExecuteUbergraph_F_SML_CAU_Sarah_Head_01_Dyn_AnimBP) == 0x000004, "Wrong size on F_SML_CAU_Sarah_Head_01_Dyn_AnimBP_C_ExecuteUbergraph_F_SML_CAU_Sarah_Head_01_Dyn_AnimBP");
static_assert(offsetof(F_SML_CAU_Sarah_Head_01_Dyn_AnimBP_C_ExecuteUbergraph_F_SML_CAU_Sarah_Head_01_Dyn_AnimBP, EntryPoint) == 0x000000, "Member 'F_SML_CAU_Sarah_Head_01_Dyn_AnimBP_C_ExecuteUbergraph_F_SML_CAU_Sarah_Head_01_Dyn_AnimBP::EntryPoint' has a wrong offset!");

}

