#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_PopupGrenadeWithTrajectory

#include "Basic.hpp"

#include "GA_Athena_ProjWithTrajectory_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_PopupGrenadeWithTrajectory.GA_Athena_PopupGrenadeWithTrajectory_C
// 0x0000 (0x0D58 - 0x0D58)
class UGA_Athena_PopupGrenadeWithTrajectory_C final : public UGA_Athena_ProjWithTrajectory_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_PopupGrenadeWithTrajectory_C">();
	}
	static class UGA_Athena_PopupGrenadeWithTrajectory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_PopupGrenadeWithTrajectory_C>();
	}
};
static_assert(alignof(UGA_Athena_PopupGrenadeWithTrajectory_C) == 0x000008, "Wrong alignment on UGA_Athena_PopupGrenadeWithTrajectory_C");
static_assert(sizeof(UGA_Athena_PopupGrenadeWithTrajectory_C) == 0x000D58, "Wrong size on UGA_Athena_PopupGrenadeWithTrajectory_C");

}

