#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_TowerGrenadeWithTrajectory

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Athena_ProjWithTrajectory_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_TowerGrenadeWithTrajectory.GA_Athena_TowerGrenadeWithTrajectory_C
// 0x0018 (0x0D70 - 0x0D58)
class UGA_Athena_TowerGrenadeWithTrajectory_C final : public UGA_Athena_ProjWithTrajectory_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Athena_TowerGrenadeWithTrajectory_C; // 0x0D58(0x0008)(Transient, DuplicateTransient)
	class ABP_ProjectileTrajectory_C*             ProjectileTrajectoryRed;                           // 0x0D60(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 TrajectoryIndicatorRedClass;                       // 0x0D68(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Athena_TowerGrenadeWithTrajectory(int32 EntryPoint);
	void CleanupTrajectoryDisplay();
	void K2_ActivateAbility();
	void SetupDummyProjectileRed();
	void UpdateTrajectorySpline();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_TowerGrenadeWithTrajectory_C">();
	}
	static class UGA_Athena_TowerGrenadeWithTrajectory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_TowerGrenadeWithTrajectory_C>();
	}
};
static_assert(alignof(UGA_Athena_TowerGrenadeWithTrajectory_C) == 0x000008, "Wrong alignment on UGA_Athena_TowerGrenadeWithTrajectory_C");
static_assert(sizeof(UGA_Athena_TowerGrenadeWithTrajectory_C) == 0x000D70, "Wrong size on UGA_Athena_TowerGrenadeWithTrajectory_C");
static_assert(offsetof(UGA_Athena_TowerGrenadeWithTrajectory_C, UberGraphFrame_GA_Athena_TowerGrenadeWithTrajectory_C) == 0x000D58, "Member 'UGA_Athena_TowerGrenadeWithTrajectory_C::UberGraphFrame_GA_Athena_TowerGrenadeWithTrajectory_C' has a wrong offset!");
static_assert(offsetof(UGA_Athena_TowerGrenadeWithTrajectory_C, ProjectileTrajectoryRed) == 0x000D60, "Member 'UGA_Athena_TowerGrenadeWithTrajectory_C::ProjectileTrajectoryRed' has a wrong offset!");
static_assert(offsetof(UGA_Athena_TowerGrenadeWithTrajectory_C, TrajectoryIndicatorRedClass) == 0x000D68, "Member 'UGA_Athena_TowerGrenadeWithTrajectory_C::TrajectoryIndicatorRedClass' has a wrong offset!");

}

