#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GAB_SurvivorApplyKnockback

#include "Basic.hpp"

#include "GAB_GenericApplyKnockback_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GAB_SurvivorApplyKnockback.GAB_SurvivorApplyKnockback_C
// 0x0000 (0x0BD0 - 0x0BD0)
class UGAB_SurvivorApplyKnockback_C final : public UGAB_GenericApplyKnockback_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GAB_SurvivorApplyKnockback_C">();
	}
	static class UGAB_SurvivorApplyKnockback_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGAB_SurvivorApplyKnockback_C>();
	}
};
static_assert(alignof(UGAB_SurvivorApplyKnockback_C) == 0x000008, "Wrong alignment on UGAB_SurvivorApplyKnockback_C");
static_assert(sizeof(UGAB_SurvivorApplyKnockback_C) == 0x000BD0, "Wrong size on UGAB_SurvivorApplyKnockback_C");

}

