#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GAB_ShielderAttachPawnEvents

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GAB_ShielderAttachPawnEvents.GAB_ShielderAttachPawnEvents_C
// 0x0020 (0x0B08 - 0x0AE8)
class UGAB_ShielderAttachPawnEvents_C final : public UFortGameplayAbility
{
public:
	uint8                                         Pad_AE8[0x8];                                      // 0x0AE8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AF0(0x0008)(Transient, DuplicateTransient)
	bool                                          Debug;                                             // 0x0AF8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_AF9[0x7];                                      // 0x0AF9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AShielderPawn_C*                        Shielder;                                          // 0x0B00(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GAB_ShielderAttachPawnEvents(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GAB_ShielderAttachPawnEvents_C">();
	}
	static class UGAB_ShielderAttachPawnEvents_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGAB_ShielderAttachPawnEvents_C>();
	}
};
static_assert(alignof(UGAB_ShielderAttachPawnEvents_C) == 0x000008, "Wrong alignment on UGAB_ShielderAttachPawnEvents_C");
static_assert(sizeof(UGAB_ShielderAttachPawnEvents_C) == 0x000B08, "Wrong size on UGAB_ShielderAttachPawnEvents_C");
static_assert(offsetof(UGAB_ShielderAttachPawnEvents_C, UberGraphFrame) == 0x000AF0, "Member 'UGAB_ShielderAttachPawnEvents_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UGAB_ShielderAttachPawnEvents_C, Debug) == 0x000AF8, "Member 'UGAB_ShielderAttachPawnEvents_C::Debug' has a wrong offset!");
static_assert(offsetof(UGAB_ShielderAttachPawnEvents_C, Shielder) == 0x000B00, "Member 'UGAB_ShielderAttachPawnEvents_C::Shielder' has a wrong offset!");

}

