#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GAB_ShielderSummonShield

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function GAB_ShielderSummonShield.GAB_ShielderSummonShield_C.ExecuteUbergraph_GAB_ShielderSummonShield
// 0x01A8 (0x01A8 - 0x0000)
struct GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)> K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_TargetData12;                   // 0x0018(0x0020)(ConstParm)
	struct FGameplayTag                           K2Node_CustomEvent_ApplicationTag12;               // 0x0038(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_TargetData1;                    // 0x0040(0x0020)(ConstParm)
	struct FGameplayTag                           K2Node_CustomEvent_ApplicationTag1;                // 0x0060(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void(struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)> K2Node_CreateDelegate_OutputDelegate1;             // 0x0068(0x0010)(ZeroConstructor, NoDestructor)
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_TargetData;                     // 0x0078(0x0020)(ConstParm)
	struct FGameplayTag                           K2Node_CustomEvent_ApplicationTag;                 // 0x0098(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void(struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)> K2Node_CreateDelegate_OutputDelegate12;            // 0x00A0(0x0010)(ZeroConstructor, NoDestructor)
	struct FGameplayTag                           Temp_struct_Variable;                              // 0x00B0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       Temp_struct_Variable1;                             // 0x00B8(0x0020)()
	bool                                          CallFunc_K2_CommitAbility_ReturnValue;             // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     K2Node_Event_EventData;                            // 0x00E0(0x00A8)(ConstParm)
	class UFortAbilityTask_PlayMontageWaitTarget* CallFunc_PlayMontageInfoAndWaitForTrigger_ReturnValue; // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPawn*                              CallFunc_GetActivatingPawn_ReturnValue;            // 0x0190(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AShielderPawn_C*                        K2Node_DynamicCast_AsShielder_Pawn;                // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x01A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield) == 0x000008, "Wrong alignment on GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield");
static_assert(sizeof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield) == 0x0001A8, "Wrong size on GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, EntryPoint) == 0x000000, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::EntryPoint' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, K2Node_CustomEvent_TargetData12) == 0x000018, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::K2Node_CustomEvent_TargetData12' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, K2Node_CustomEvent_ApplicationTag12) == 0x000038, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::K2Node_CustomEvent_ApplicationTag12' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, K2Node_CustomEvent_TargetData1) == 0x000040, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::K2Node_CustomEvent_TargetData1' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, K2Node_CustomEvent_ApplicationTag1) == 0x000060, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::K2Node_CustomEvent_ApplicationTag1' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, K2Node_CreateDelegate_OutputDelegate1) == 0x000068, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::K2Node_CreateDelegate_OutputDelegate1' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, K2Node_CustomEvent_TargetData) == 0x000078, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::K2Node_CustomEvent_TargetData' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, K2Node_CustomEvent_ApplicationTag) == 0x000098, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::K2Node_CustomEvent_ApplicationTag' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, K2Node_CreateDelegate_OutputDelegate12) == 0x0000A0, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::K2Node_CreateDelegate_OutputDelegate12' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, Temp_struct_Variable) == 0x0000B0, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, Temp_struct_Variable1) == 0x0000B8, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::Temp_struct_Variable1' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, CallFunc_K2_CommitAbility_ReturnValue) == 0x0000D8, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::CallFunc_K2_CommitAbility_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, K2Node_Event_EventData) == 0x0000E0, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::K2Node_Event_EventData' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, CallFunc_PlayMontageInfoAndWaitForTrigger_ReturnValue) == 0x000188, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::CallFunc_PlayMontageInfoAndWaitForTrigger_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, CallFunc_GetActivatingPawn_ReturnValue) == 0x000190, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::CallFunc_GetActivatingPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, K2Node_DynamicCast_AsShielder_Pawn) == 0x000198, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::K2Node_DynamicCast_AsShielder_Pawn' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, K2Node_DynamicCast_bSuccess) == 0x0001A0, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield, CallFunc_IsValid_ReturnValue) == 0x0001A1, "Member 'GAB_ShielderSummonShield_C_ExecuteUbergraph_GAB_ShielderSummonShield::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function GAB_ShielderSummonShield.GAB_ShielderSummonShield_C.Cancelled_A740968F4C3C1AF2475795BD1818ADA3
// 0x0028 (0x0028 - 0x0000)
struct GAB_ShielderSummonShield_C_Cancelled_A740968F4C3C1AF2475795BD1818ADA3 final
{
public:
	struct FGameplayAbilityTargetDataHandle       TargetData;                                        // 0x0000(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FGameplayTag                           ApplicationTag;                                    // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_ShielderSummonShield_C_Cancelled_A740968F4C3C1AF2475795BD1818ADA3) == 0x000008, "Wrong alignment on GAB_ShielderSummonShield_C_Cancelled_A740968F4C3C1AF2475795BD1818ADA3");
static_assert(sizeof(GAB_ShielderSummonShield_C_Cancelled_A740968F4C3C1AF2475795BD1818ADA3) == 0x000028, "Wrong size on GAB_ShielderSummonShield_C_Cancelled_A740968F4C3C1AF2475795BD1818ADA3");
static_assert(offsetof(GAB_ShielderSummonShield_C_Cancelled_A740968F4C3C1AF2475795BD1818ADA3, TargetData) == 0x000000, "Member 'GAB_ShielderSummonShield_C_Cancelled_A740968F4C3C1AF2475795BD1818ADA3::TargetData' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_Cancelled_A740968F4C3C1AF2475795BD1818ADA3, ApplicationTag) == 0x000020, "Member 'GAB_ShielderSummonShield_C_Cancelled_A740968F4C3C1AF2475795BD1818ADA3::ApplicationTag' has a wrong offset!");

// Function GAB_ShielderSummonShield.GAB_ShielderSummonShield_C.Completed_A740968F4C3C1AF2475795BD1818ADA3
// 0x0028 (0x0028 - 0x0000)
struct GAB_ShielderSummonShield_C_Completed_A740968F4C3C1AF2475795BD1818ADA3 final
{
public:
	struct FGameplayAbilityTargetDataHandle       TargetData;                                        // 0x0000(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FGameplayTag                           ApplicationTag;                                    // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_ShielderSummonShield_C_Completed_A740968F4C3C1AF2475795BD1818ADA3) == 0x000008, "Wrong alignment on GAB_ShielderSummonShield_C_Completed_A740968F4C3C1AF2475795BD1818ADA3");
static_assert(sizeof(GAB_ShielderSummonShield_C_Completed_A740968F4C3C1AF2475795BD1818ADA3) == 0x000028, "Wrong size on GAB_ShielderSummonShield_C_Completed_A740968F4C3C1AF2475795BD1818ADA3");
static_assert(offsetof(GAB_ShielderSummonShield_C_Completed_A740968F4C3C1AF2475795BD1818ADA3, TargetData) == 0x000000, "Member 'GAB_ShielderSummonShield_C_Completed_A740968F4C3C1AF2475795BD1818ADA3::TargetData' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_Completed_A740968F4C3C1AF2475795BD1818ADA3, ApplicationTag) == 0x000020, "Member 'GAB_ShielderSummonShield_C_Completed_A740968F4C3C1AF2475795BD1818ADA3::ApplicationTag' has a wrong offset!");

// Function GAB_ShielderSummonShield.GAB_ShielderSummonShield_C.K2_ActivateAbilityFromEvent
// 0x00A8 (0x00A8 - 0x0000)
struct GAB_ShielderSummonShield_C_K2_ActivateAbilityFromEvent final
{
public:
	struct FGameplayEventData                     EventData;                                         // 0x0000(0x00A8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(GAB_ShielderSummonShield_C_K2_ActivateAbilityFromEvent) == 0x000008, "Wrong alignment on GAB_ShielderSummonShield_C_K2_ActivateAbilityFromEvent");
static_assert(sizeof(GAB_ShielderSummonShield_C_K2_ActivateAbilityFromEvent) == 0x0000A8, "Wrong size on GAB_ShielderSummonShield_C_K2_ActivateAbilityFromEvent");
static_assert(offsetof(GAB_ShielderSummonShield_C_K2_ActivateAbilityFromEvent, EventData) == 0x000000, "Member 'GAB_ShielderSummonShield_C_K2_ActivateAbilityFromEvent::EventData' has a wrong offset!");

// Function GAB_ShielderSummonShield.GAB_ShielderSummonShield_C.Triggered_A740968F4C3C1AF2475795BD1818ADA3
// 0x0028 (0x0028 - 0x0000)
struct GAB_ShielderSummonShield_C_Triggered_A740968F4C3C1AF2475795BD1818ADA3 final
{
public:
	struct FGameplayAbilityTargetDataHandle       TargetData;                                        // 0x0000(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FGameplayTag                           ApplicationTag;                                    // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_ShielderSummonShield_C_Triggered_A740968F4C3C1AF2475795BD1818ADA3) == 0x000008, "Wrong alignment on GAB_ShielderSummonShield_C_Triggered_A740968F4C3C1AF2475795BD1818ADA3");
static_assert(sizeof(GAB_ShielderSummonShield_C_Triggered_A740968F4C3C1AF2475795BD1818ADA3) == 0x000028, "Wrong size on GAB_ShielderSummonShield_C_Triggered_A740968F4C3C1AF2475795BD1818ADA3");
static_assert(offsetof(GAB_ShielderSummonShield_C_Triggered_A740968F4C3C1AF2475795BD1818ADA3, TargetData) == 0x000000, "Member 'GAB_ShielderSummonShield_C_Triggered_A740968F4C3C1AF2475795BD1818ADA3::TargetData' has a wrong offset!");
static_assert(offsetof(GAB_ShielderSummonShield_C_Triggered_A740968F4C3C1AF2475795BD1818ADA3, ApplicationTag) == 0x000020, "Member 'GAB_ShielderSummonShield_C_Triggered_A740968F4C3C1AF2475795BD1818ADA3::ApplicationTag' has a wrong offset!");

}

