#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GAB_HuskFrustration

#include "Basic.hpp"

#include "GAB_HuskFrustration_classes.hpp"
#include "GAB_HuskFrustration_parameters.hpp"


namespace SDK
{

// Function GAB_HuskFrustration.GAB_HuskFrustration_C.ExecuteUbergraph_GAB_HuskFrustration
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGAB_HuskFrustration_C::ExecuteUbergraph_GAB_HuskFrustration(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GAB_HuskFrustration_C", "ExecuteUbergraph_GAB_HuskFrustration");

	Params::GAB_HuskFrustration_C_ExecuteUbergraph_GAB_HuskFrustration Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GAB_HuskFrustration.GAB_HuskFrustration_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGAB_HuskFrustration_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GAB_HuskFrustration_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}

}

