#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GAB_SurvivorRescue

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function GAB_SurvivorRescue.GAB_SurvivorRescue_C.ExecuteUbergraph_GAB_SurvivorRescue
// 0x0440 (0x0440 - 0x0000)
struct GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPawn*                              CallFunc_GetActivatingPawn_ReturnValue;            // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASurvivor_C*                            K2Node_DynamicCast_AsSurvivor;                     // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)> K2Node_CreateDelegate_OutputDelegate;              // 0x0020(0x0010)(ZeroConstructor, NoDestructor)
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_TargetData12;                   // 0x0030(0x0020)(ConstParm)
	struct FGameplayTag                           K2Node_CustomEvent_ApplicationTag12;               // 0x0050(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_TargetData1;                    // 0x0058(0x0020)(ConstParm)
	struct FGameplayTag                           K2Node_CustomEvent_ApplicationTag1;                // 0x0078(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void(struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)> K2Node_CreateDelegate_OutputDelegate1;             // 0x0080(0x0010)(ZeroConstructor, NoDestructor)
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_TargetData;                     // 0x0090(0x0020)(ConstParm)
	struct FGameplayTag                           K2Node_CustomEvent_ApplicationTag;                 // 0x00B0(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void(struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)> K2Node_CreateDelegate_OutputDelegate12;            // 0x00B8(0x0010)(ZeroConstructor, NoDestructor)
	struct FGameplayTag                           Temp_struct_Variable;                              // 0x00C8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       Temp_struct_Variable1;                             // 0x00D0(0x0020)()
	struct FGameplayEventData                     K2Node_CustomEvent_Payload;                        // 0x00F0(0x00A8)()
	TDelegate<void(const struct FGameplayEventData& Payload)> K2Node_CreateDelegate_OutputDelegate123;           // 0x0198(0x0010)(ZeroConstructor, NoDestructor)
	struct FGameplayEventData                     Temp_struct_Variable12;                            // 0x01A8(0x00A8)()
	class UAbilityTask_WaitGameplayEvent*         CallFunc_WaitGameplayEvent_ReturnValue;            // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_259[0x7];                                      // 0x0259(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPawn*                              CallFunc_GetActivatingPawn_ReturnValue1;           // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPawn*                              CallFunc_GetActivatingPawn_ReturnValue12;          // 0x0268(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortAbilityTask_PlayMontageWaitTarget* CallFunc_PlayMontageInfoAndWaitForTrigger_ReturnValue; // 0x0270(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0278(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue1;                     // 0x0284(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_285[0x3];                                      // 0x0285(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue;      // 0x0288(0x000C)(IsPlainOldData, NoDestructor)
	uint8                                         Pad_294[0xC];                                      // 0x0294(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x02A0(0x0030)(IsPlainOldData, NoDestructor)
	struct FGameplayEventData                     K2Node_Event_EventData;                            // 0x02D0(0x00A8)(ConstParm)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0378(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue;          // 0x0380(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerController*                  K2Node_DynamicCast_AsFort_Player_Controller;       // 0x0388(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess1;                      // 0x0390(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_391[0x7];                                      // 0x0391(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPawn*                              CallFunc_GetActivatingPawn_ReturnValue123;         // 0x0398(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortAIPawn*                            K2Node_DynamicCast_AsFort_AIPawn;                  // 0x03A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess12;                     // 0x03A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_CommitAbility_ReturnValue;             // 0x03A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3AA[0x6];                                      // 0x03AA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPawn*                              CallFunc_GetActivatingPawn_ReturnValue1234;        // 0x03B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortAIPawn*                            K2Node_DynamicCast_AsFort_AIPawn1;                 // 0x03B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess123;                    // 0x03C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3C1[0x7];                                      // 0x03C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue;                  // 0x03C8(0x0008)(NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate1234;          // 0x03D0(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          K2Node_Event_bWasCancelled;                        // 0x03E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3E1[0x7];                                      // 0x03E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x03E8(0x0008)(NoDestructor)
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x03F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortGameStateZone*                     K2Node_DynamicCast_AsFort_Game_State_Zone;         // 0x03F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess1234;                   // 0x0400(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_401[0x7];                                      // 0x0401(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPawn*                              CallFunc_GetActivatingPawn_ReturnValue12345;       // 0x0408(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0410(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           CallFunc_MakeLiteralGameplayTag_ReturnValue;       // 0x0418(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetClassDisplayName_ReturnValue;          // 0x0420(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_MatchesTag_ReturnValue;                   // 0x0430(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_431[0x3];                                      // 0x0431(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_MakeLiteralFloat_ReturnValue;             // 0x0434(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue) == 0x000010, "Wrong alignment on GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue");
static_assert(sizeof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue) == 0x000440, "Wrong size on GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, EntryPoint) == 0x000000, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::EntryPoint' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_GetActivatingPawn_ReturnValue) == 0x000008, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_GetActivatingPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_DynamicCast_AsSurvivor) == 0x000010, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_DynamicCast_AsSurvivor' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_CreateDelegate_OutputDelegate) == 0x000020, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_CustomEvent_TargetData12) == 0x000030, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_CustomEvent_TargetData12' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_CustomEvent_ApplicationTag12) == 0x000050, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_CustomEvent_ApplicationTag12' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_CustomEvent_TargetData1) == 0x000058, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_CustomEvent_TargetData1' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_CustomEvent_ApplicationTag1) == 0x000078, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_CustomEvent_ApplicationTag1' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_CreateDelegate_OutputDelegate1) == 0x000080, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_CreateDelegate_OutputDelegate1' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_CustomEvent_TargetData) == 0x000090, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_CustomEvent_TargetData' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_CustomEvent_ApplicationTag) == 0x0000B0, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_CustomEvent_ApplicationTag' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_CreateDelegate_OutputDelegate12) == 0x0000B8, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_CreateDelegate_OutputDelegate12' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, Temp_struct_Variable) == 0x0000C8, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, Temp_struct_Variable1) == 0x0000D0, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::Temp_struct_Variable1' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_CustomEvent_Payload) == 0x0000F0, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_CustomEvent_Payload' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_CreateDelegate_OutputDelegate123) == 0x000198, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_CreateDelegate_OutputDelegate123' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, Temp_struct_Variable12) == 0x0001A8, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::Temp_struct_Variable12' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_WaitGameplayEvent_ReturnValue) == 0x000250, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_WaitGameplayEvent_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_IsValid_ReturnValue) == 0x000258, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_GetActivatingPawn_ReturnValue1) == 0x000260, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_GetActivatingPawn_ReturnValue1' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_GetActivatingPawn_ReturnValue12) == 0x000268, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_GetActivatingPawn_ReturnValue12' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_PlayMontageInfoAndWaitForTrigger_ReturnValue) == 0x000270, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_PlayMontageInfoAndWaitForTrigger_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000278, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_IsValid_ReturnValue1) == 0x000284, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_IsValid_ReturnValue1' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_K2_GetComponentRotation_ReturnValue) == 0x000288, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_K2_GetComponentRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_MakeTransform_ReturnValue) == 0x0002A0, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_Event_EventData) == 0x0002D0, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_Event_EventData' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000378, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_FinishSpawningActor_ReturnValue) == 0x000380, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_DynamicCast_AsFort_Player_Controller) == 0x000388, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_DynamicCast_AsFort_Player_Controller' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_DynamicCast_bSuccess1) == 0x000390, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_DynamicCast_bSuccess1' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_GetActivatingPawn_ReturnValue123) == 0x000398, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_GetActivatingPawn_ReturnValue123' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_DynamicCast_AsFort_AIPawn) == 0x0003A0, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_DynamicCast_AsFort_AIPawn' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_DynamicCast_bSuccess12) == 0x0003A8, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_DynamicCast_bSuccess12' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_K2_CommitAbility_ReturnValue) == 0x0003A9, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_K2_CommitAbility_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_GetActivatingPawn_ReturnValue1234) == 0x0003B0, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_GetActivatingPawn_ReturnValue1234' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_DynamicCast_AsFort_AIPawn1) == 0x0003B8, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_DynamicCast_AsFort_AIPawn1' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_DynamicCast_bSuccess123) == 0x0003C0, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_DynamicCast_bSuccess123' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_K2_SetTimer_ReturnValue) == 0x0003C8, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_K2_SetTimer_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_CreateDelegate_OutputDelegate1234) == 0x0003D0, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_CreateDelegate_OutputDelegate1234' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_Event_bWasCancelled) == 0x0003E0, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_Event_bWasCancelled' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x0003E8, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_GetGameState_ReturnValue) == 0x0003F0, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_GetGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_DynamicCast_AsFort_Game_State_Zone) == 0x0003F8, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_DynamicCast_AsFort_Game_State_Zone' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, K2Node_DynamicCast_bSuccess1234) == 0x000400, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::K2Node_DynamicCast_bSuccess1234' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_GetActivatingPawn_ReturnValue12345) == 0x000408, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_GetActivatingPawn_ReturnValue12345' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_GetObjectClass_ReturnValue) == 0x000410, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_MakeLiteralGameplayTag_ReturnValue) == 0x000418, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_MakeLiteralGameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_GetClassDisplayName_ReturnValue) == 0x000420, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_GetClassDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_MatchesTag_ReturnValue) == 0x000430, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_MatchesTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue, CallFunc_MakeLiteralFloat_ReturnValue) == 0x000434, "Member 'GAB_SurvivorRescue_C_ExecuteUbergraph_GAB_SurvivorRescue::CallFunc_MakeLiteralFloat_ReturnValue' has a wrong offset!");

// Function GAB_SurvivorRescue.GAB_SurvivorRescue_C.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct GAB_SurvivorRescue_C_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GAB_SurvivorRescue_C_K2_OnEndAbility) == 0x000001, "Wrong alignment on GAB_SurvivorRescue_C_K2_OnEndAbility");
static_assert(sizeof(GAB_SurvivorRescue_C_K2_OnEndAbility) == 0x000001, "Wrong size on GAB_SurvivorRescue_C_K2_OnEndAbility");
static_assert(offsetof(GAB_SurvivorRescue_C_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'GAB_SurvivorRescue_C_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

// Function GAB_SurvivorRescue.GAB_SurvivorRescue_C.Cancelled_8BD132F745BDCD15EBF232861F392E7B
// 0x0028 (0x0028 - 0x0000)
struct GAB_SurvivorRescue_C_Cancelled_8BD132F745BDCD15EBF232861F392E7B final
{
public:
	struct FGameplayAbilityTargetDataHandle       TargetData;                                        // 0x0000(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FGameplayTag                           ApplicationTag;                                    // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_SurvivorRescue_C_Cancelled_8BD132F745BDCD15EBF232861F392E7B) == 0x000008, "Wrong alignment on GAB_SurvivorRescue_C_Cancelled_8BD132F745BDCD15EBF232861F392E7B");
static_assert(sizeof(GAB_SurvivorRescue_C_Cancelled_8BD132F745BDCD15EBF232861F392E7B) == 0x000028, "Wrong size on GAB_SurvivorRescue_C_Cancelled_8BD132F745BDCD15EBF232861F392E7B");
static_assert(offsetof(GAB_SurvivorRescue_C_Cancelled_8BD132F745BDCD15EBF232861F392E7B, TargetData) == 0x000000, "Member 'GAB_SurvivorRescue_C_Cancelled_8BD132F745BDCD15EBF232861F392E7B::TargetData' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_Cancelled_8BD132F745BDCD15EBF232861F392E7B, ApplicationTag) == 0x000020, "Member 'GAB_SurvivorRescue_C_Cancelled_8BD132F745BDCD15EBF232861F392E7B::ApplicationTag' has a wrong offset!");

// Function GAB_SurvivorRescue.GAB_SurvivorRescue_C.Completed_8BD132F745BDCD15EBF232861F392E7B
// 0x0028 (0x0028 - 0x0000)
struct GAB_SurvivorRescue_C_Completed_8BD132F745BDCD15EBF232861F392E7B final
{
public:
	struct FGameplayAbilityTargetDataHandle       TargetData;                                        // 0x0000(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FGameplayTag                           ApplicationTag;                                    // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_SurvivorRescue_C_Completed_8BD132F745BDCD15EBF232861F392E7B) == 0x000008, "Wrong alignment on GAB_SurvivorRescue_C_Completed_8BD132F745BDCD15EBF232861F392E7B");
static_assert(sizeof(GAB_SurvivorRescue_C_Completed_8BD132F745BDCD15EBF232861F392E7B) == 0x000028, "Wrong size on GAB_SurvivorRescue_C_Completed_8BD132F745BDCD15EBF232861F392E7B");
static_assert(offsetof(GAB_SurvivorRescue_C_Completed_8BD132F745BDCD15EBF232861F392E7B, TargetData) == 0x000000, "Member 'GAB_SurvivorRescue_C_Completed_8BD132F745BDCD15EBF232861F392E7B::TargetData' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_Completed_8BD132F745BDCD15EBF232861F392E7B, ApplicationTag) == 0x000020, "Member 'GAB_SurvivorRescue_C_Completed_8BD132F745BDCD15EBF232861F392E7B::ApplicationTag' has a wrong offset!");

// Function GAB_SurvivorRescue.GAB_SurvivorRescue_C.EventReceived_AE3E49574CEC70DFC62B01973CCF7515
// 0x00A8 (0x00A8 - 0x0000)
struct GAB_SurvivorRescue_C_EventReceived_AE3E49574CEC70DFC62B01973CCF7515 final
{
public:
	struct FGameplayEventData                     Payload;                                           // 0x0000(0x00A8)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(GAB_SurvivorRescue_C_EventReceived_AE3E49574CEC70DFC62B01973CCF7515) == 0x000008, "Wrong alignment on GAB_SurvivorRescue_C_EventReceived_AE3E49574CEC70DFC62B01973CCF7515");
static_assert(sizeof(GAB_SurvivorRescue_C_EventReceived_AE3E49574CEC70DFC62B01973CCF7515) == 0x0000A8, "Wrong size on GAB_SurvivorRescue_C_EventReceived_AE3E49574CEC70DFC62B01973CCF7515");
static_assert(offsetof(GAB_SurvivorRescue_C_EventReceived_AE3E49574CEC70DFC62B01973CCF7515, Payload) == 0x000000, "Member 'GAB_SurvivorRescue_C_EventReceived_AE3E49574CEC70DFC62B01973CCF7515::Payload' has a wrong offset!");

// Function GAB_SurvivorRescue.GAB_SurvivorRescue_C.K2_ActivateAbilityFromEvent
// 0x00A8 (0x00A8 - 0x0000)
struct GAB_SurvivorRescue_C_K2_ActivateAbilityFromEvent final
{
public:
	struct FGameplayEventData                     EventData;                                         // 0x0000(0x00A8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(GAB_SurvivorRescue_C_K2_ActivateAbilityFromEvent) == 0x000008, "Wrong alignment on GAB_SurvivorRescue_C_K2_ActivateAbilityFromEvent");
static_assert(sizeof(GAB_SurvivorRescue_C_K2_ActivateAbilityFromEvent) == 0x0000A8, "Wrong size on GAB_SurvivorRescue_C_K2_ActivateAbilityFromEvent");
static_assert(offsetof(GAB_SurvivorRescue_C_K2_ActivateAbilityFromEvent, EventData) == 0x000000, "Member 'GAB_SurvivorRescue_C_K2_ActivateAbilityFromEvent::EventData' has a wrong offset!");

// Function GAB_SurvivorRescue.GAB_SurvivorRescue_C.Triggered_8BD132F745BDCD15EBF232861F392E7B
// 0x0028 (0x0028 - 0x0000)
struct GAB_SurvivorRescue_C_Triggered_8BD132F745BDCD15EBF232861F392E7B final
{
public:
	struct FGameplayAbilityTargetDataHandle       TargetData;                                        // 0x0000(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FGameplayTag                           ApplicationTag;                                    // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_SurvivorRescue_C_Triggered_8BD132F745BDCD15EBF232861F392E7B) == 0x000008, "Wrong alignment on GAB_SurvivorRescue_C_Triggered_8BD132F745BDCD15EBF232861F392E7B");
static_assert(sizeof(GAB_SurvivorRescue_C_Triggered_8BD132F745BDCD15EBF232861F392E7B) == 0x000028, "Wrong size on GAB_SurvivorRescue_C_Triggered_8BD132F745BDCD15EBF232861F392E7B");
static_assert(offsetof(GAB_SurvivorRescue_C_Triggered_8BD132F745BDCD15EBF232861F392E7B, TargetData) == 0x000000, "Member 'GAB_SurvivorRescue_C_Triggered_8BD132F745BDCD15EBF232861F392E7B::TargetData' has a wrong offset!");
static_assert(offsetof(GAB_SurvivorRescue_C_Triggered_8BD132F745BDCD15EBF232861F392E7B, ApplicationTag) == 0x000020, "Member 'GAB_SurvivorRescue_C_Triggered_8BD132F745BDCD15EBF232861F392E7B::ApplicationTag' has a wrong offset!");

}

