#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GAB_FlingerMeleeSwipe

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GAB_FlingerMeleeSwipe.GAB_FlingerMeleeSwipe_C
// 0x0018 (0x0B00 - 0x0AE8)
class UGAB_FlingerMeleeSwipe_C final : public UFortGameplayAbility
{
public:
	uint8                                         Pad_AE8[0x8];                                      // 0x0AE8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AF0(0x0008)(Transient, DuplicateTransient)
	class FName                                   MontageSectionToPlay;                              // 0x0AF8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GAB_FlingerMeleeSwipe(int32 EntryPoint);
	void Cancelled_75D3277A479B3F48D2AD2889328C3F32(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void Completed_75D3277A479B3F48D2AD2889328C3F32(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void K2_ActivateAbility();
	void Triggered_75D3277A479B3F48D2AD2889328C3F32(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GAB_FlingerMeleeSwipe_C">();
	}
	static class UGAB_FlingerMeleeSwipe_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGAB_FlingerMeleeSwipe_C>();
	}
};
static_assert(alignof(UGAB_FlingerMeleeSwipe_C) == 0x000008, "Wrong alignment on UGAB_FlingerMeleeSwipe_C");
static_assert(sizeof(UGAB_FlingerMeleeSwipe_C) == 0x000B00, "Wrong size on UGAB_FlingerMeleeSwipe_C");
static_assert(offsetof(UGAB_FlingerMeleeSwipe_C, UberGraphFrame) == 0x000AF0, "Member 'UGAB_FlingerMeleeSwipe_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UGAB_FlingerMeleeSwipe_C, MontageSectionToPlay) == 0x000AF8, "Member 'UGAB_FlingerMeleeSwipe_C::MontageSectionToPlay' has a wrong offset!");

}

