#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_HitEmWhileTheyReDown_Burst

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_HitEmWhileTheyReDown_Burst.GC_HitEmWhileTheyReDown_Burst_C
// 0x0000 (0x00B0 - 0x00B0)
class UGC_HitEmWhileTheyReDown_Burst_C final : public UFortGameplayCueNotify_Simple
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_HitEmWhileTheyReDown_Burst_C">();
	}
	static class UGC_HitEmWhileTheyReDown_Burst_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_HitEmWhileTheyReDown_Burst_C>();
	}
};
static_assert(alignof(UGC_HitEmWhileTheyReDown_Burst_C) == 0x000010, "Wrong alignment on UGC_HitEmWhileTheyReDown_Burst_C");
static_assert(sizeof(UGC_HitEmWhileTheyReDown_Burst_C) == 0x0000B0, "Wrong size on UGC_HitEmWhileTheyReDown_Burst_C");

}

