#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Ninja_SmokeBomb_ImpactFX

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Ninja_SmokeBomb_ImpactFX.GC_Ninja_SmokeBomb_ImpactFX_C
// 0x0010 (0x00C0 - 0x00B0)
class UGC_Ninja_SmokeBomb_ImpactFX_C final : public UFortGameplayCueNotify_Simple
{
public:
	class UForceFeedbackEffect*                   SmokeBombForceFeedbackNear;                        // 0x00B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UForceFeedbackEffect*                   SmokeBombForceFeedbackFar;                         // 0x00B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Ninja_SmokeBomb_ImpactFX_C">();
	}
	static class UGC_Ninja_SmokeBomb_ImpactFX_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_Ninja_SmokeBomb_ImpactFX_C>();
	}
};
static_assert(alignof(UGC_Ninja_SmokeBomb_ImpactFX_C) == 0x000010, "Wrong alignment on UGC_Ninja_SmokeBomb_ImpactFX_C");
static_assert(sizeof(UGC_Ninja_SmokeBomb_ImpactFX_C) == 0x0000C0, "Wrong size on UGC_Ninja_SmokeBomb_ImpactFX_C");
static_assert(offsetof(UGC_Ninja_SmokeBomb_ImpactFX_C, SmokeBombForceFeedbackNear) == 0x0000B0, "Member 'UGC_Ninja_SmokeBomb_ImpactFX_C::SmokeBombForceFeedbackNear' has a wrong offset!");
static_assert(offsetof(UGC_Ninja_SmokeBomb_ImpactFX_C, SmokeBombForceFeedbackFar) == 0x0000B8, "Member 'UGC_Ninja_SmokeBomb_ImpactFX_C::SmokeBombForceFeedbackFar' has a wrong offset!");

}

