#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Teleport_in

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Teleport_in.GC_Teleport_In_C
// 0x0010 (0x00C0 - 0x00B0)
class UGC_Teleport_In_C final : public UFortGameplayCueNotify_Simple
{
public:
	float                                         Default_Play_Length;                               // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Teleport_In_C">();
	}
	static class UGC_Teleport_In_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_Teleport_In_C>();
	}
};
static_assert(alignof(UGC_Teleport_In_C) == 0x000010, "Wrong alignment on UGC_Teleport_In_C");
static_assert(sizeof(UGC_Teleport_In_C) == 0x0000C0, "Wrong size on UGC_Teleport_In_C");
static_assert(offsetof(UGC_Teleport_In_C, Default_Play_Length) == 0x0000B0, "Member 'UGC_Teleport_In_C::Default_Play_Length' has a wrong offset!");

}

