#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNS_Commando_UpCloseAndPersonal

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNS_Commando_UpCloseAndPersonal.GCNS_Commando_UpCloseAndPersonal_C
// 0x0000 (0x00B0 - 0x00B0)
class UGCNS_Commando_UpCloseAndPersonal_C final : public UFortGameplayCueNotify_Simple
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCNS_Commando_UpCloseAndPersonal_C">();
	}
	static class UGCNS_Commando_UpCloseAndPersonal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCNS_Commando_UpCloseAndPersonal_C>();
	}
};
static_assert(alignof(UGCNS_Commando_UpCloseAndPersonal_C) == 0x000010, "Wrong alignment on UGCNS_Commando_UpCloseAndPersonal_C");
static_assert(sizeof(UGCNS_Commando_UpCloseAndPersonal_C) == 0x0000B0, "Wrong size on UGCNS_Commando_UpCloseAndPersonal_C");

}

