#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HuntingGeneratorLocationContext

#include "Basic.hpp"

#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HuntingGeneratorLocationContext.HuntingGeneratorLocationContext_C
// 0x0008 (0x0038 - 0x0030)
class UHuntingGeneratorLocationContext_C final : public UEnvQueryContext_BlueprintBase
{
public:
	bool                                          Debug;                                             // 0x0030(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ProvideSingleLocation(class UObject* QuerierObject, class AActor* QuerierActor, struct FVector* ResultingLocation);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HuntingGeneratorLocationContext_C">();
	}
	static class UHuntingGeneratorLocationContext_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHuntingGeneratorLocationContext_C>();
	}
};
static_assert(alignof(UHuntingGeneratorLocationContext_C) == 0x000008, "Wrong alignment on UHuntingGeneratorLocationContext_C");
static_assert(sizeof(UHuntingGeneratorLocationContext_C) == 0x000038, "Wrong size on UHuntingGeneratorLocationContext_C");
static_assert(offsetof(UHuntingGeneratorLocationContext_C, Debug) == 0x000030, "Member 'UHuntingGeneratorLocationContext_C::Debug' has a wrong offset!");

}

