#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemReceivedFoundersRewardsHeader

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ItemReceivedHeaderSubWidgetBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ItemReceivedFoundersRewardsHeader.ItemReceivedFoundersRewardsHeader_C
// 0x0020 (0x0268 - 0x0248)
class UItemReceivedFoundersRewardsHeader_C final : public UItemReceivedHeaderSubWidgetBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_ItemReceivedFoundersRewardsHeader_C; // 0x0248(0x0008)(Transient, DuplicateTransient)
	class UCommonTextBlock*                       CommonTextBlock_0;                                 // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Subtext;                                           // 0x0258(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       TopText;                                           // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_ItemReceivedFoundersRewardsHeader(int32 EntryPoint);
	void InitFromGiftBoxItem_BP();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ItemReceivedFoundersRewardsHeader_C">();
	}
	static class UItemReceivedFoundersRewardsHeader_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemReceivedFoundersRewardsHeader_C>();
	}
};
static_assert(alignof(UItemReceivedFoundersRewardsHeader_C) == 0x000008, "Wrong alignment on UItemReceivedFoundersRewardsHeader_C");
static_assert(sizeof(UItemReceivedFoundersRewardsHeader_C) == 0x000268, "Wrong size on UItemReceivedFoundersRewardsHeader_C");
static_assert(offsetof(UItemReceivedFoundersRewardsHeader_C, UberGraphFrame_ItemReceivedFoundersRewardsHeader_C) == 0x000248, "Member 'UItemReceivedFoundersRewardsHeader_C::UberGraphFrame_ItemReceivedFoundersRewardsHeader_C' has a wrong offset!");
static_assert(offsetof(UItemReceivedFoundersRewardsHeader_C, CommonTextBlock_0) == 0x000250, "Member 'UItemReceivedFoundersRewardsHeader_C::CommonTextBlock_0' has a wrong offset!");
static_assert(offsetof(UItemReceivedFoundersRewardsHeader_C, Subtext) == 0x000258, "Member 'UItemReceivedFoundersRewardsHeader_C::Subtext' has a wrong offset!");
static_assert(offsetof(UItemReceivedFoundersRewardsHeader_C, TopText) == 0x000260, "Member 'UItemReceivedFoundersRewardsHeader_C::TopText' has a wrong offset!");

}

