#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SurvivorHitInfoType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum SurvivorHitInfoType.SurvivorHitInfoType
// NumValues: 0x0005
enum class ESurvivorHitInfoType : uint8
{
	NewEnumerator3                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator0                           = 3,
	SurvivorHitInfoType_MAX                  = 4,
};

}

