#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TracerGeneric_Athena_Cannon_Child

#include "Basic.hpp"

#include "TracerGeneric_Athena_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TracerGeneric_Athena_Cannon_Child.TracerGeneric_Athena_Cannon_Child_C
// 0x0000 (0x03D0 - 0x03D0)
class ATracerGeneric_Athena_Cannon_Child_C final : public ATracerGeneric_Athena_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TracerGeneric_Athena_Cannon_Child_C">();
	}
	static class ATracerGeneric_Athena_Cannon_Child_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATracerGeneric_Athena_Cannon_Child_C>();
	}
};
static_assert(alignof(ATracerGeneric_Athena_Cannon_Child_C) == 0x000008, "Wrong alignment on ATracerGeneric_Athena_Cannon_Child_C");
static_assert(sizeof(ATracerGeneric_Athena_Cannon_Child_C) == 0x0003D0, "Wrong size on ATracerGeneric_Athena_Cannon_Child_C");

}

