#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Trap_Ceiling_Falling

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Trap_Ceiling_Falling.Trap_Ceiling_Falling_C
// 0x00B8 (0x0FA8 - 0x0EF0)
class ATrap_Ceiling_Falling_C final : public ABuildingTrapCeiling_Falling
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0EF0(0x0008)(Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Door_2;                                            // 0x0EF8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Door_1;                                            // 0x0F00(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               P_FallingDirt;                                     // 0x0F08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tire_9;                                            // 0x0F10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tire_8;                                            // 0x0F18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tire_7;                                            // 0x0F20(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tire_6;                                            // 0x0F28(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tire_5;                                            // 0x0F30(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tire_4;                                            // 0x0F38(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tire_3;                                            // 0x0F40(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tire_2;                                            // 0x0F48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tire_1;                                            // 0x0F50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x0F58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box;                                               // 0x0F60(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Root;                                              // 0x0F68(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         OpenDoor_Rotation_679D553A46783E44EDCECCA7D120A863; // 0x0F70(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            OpenDoor__Direction_679D553A46783E44EDCECCA7D120A863; // 0x0F74(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F75[0x3];                                      // 0x0F75(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     OpenDoor;                                          // 0x0F78(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SocketTransforms;                                  // 0x0F80(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F81[0x7];                                      // 0x0F81(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UStaticMeshComponent*>           Tires;                                             // 0x0F88(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	struct FTimerHandle                           TimerHandle;                                       // 0x0F98(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	bool                                          bActivated;                                        // 0x0FA0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)

public:
	void ExecuteUbergraph_Trap_Ceiling_Falling(int32 EntryPoint);
	void CloseDoors();
	void OpenDoors();
	void FireDustFX();
	void ShowTires();
	void TrapActivated(const float CooldownDuration);
	void OnPlaced();
	void OpenDoor__UpdateFunc();
	void OpenDoor__FinishedFunc();
	void UserConstructionScript();
	void ToggleTireVisibility(bool NewHidden);
	void OnRep_bActivated();
	void ToggleDoors(bool bToggle);
	void ToggleTiresAndFX();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Trap_Ceiling_Falling_C">();
	}
	static class ATrap_Ceiling_Falling_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATrap_Ceiling_Falling_C>();
	}
};
static_assert(alignof(ATrap_Ceiling_Falling_C) == 0x000008, "Wrong alignment on ATrap_Ceiling_Falling_C");
static_assert(sizeof(ATrap_Ceiling_Falling_C) == 0x000FA8, "Wrong size on ATrap_Ceiling_Falling_C");
static_assert(offsetof(ATrap_Ceiling_Falling_C, UberGraphFrame) == 0x000EF0, "Member 'ATrap_Ceiling_Falling_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Door_2) == 0x000EF8, "Member 'ATrap_Ceiling_Falling_C::Door_2' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Door_1) == 0x000F00, "Member 'ATrap_Ceiling_Falling_C::Door_1' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, P_FallingDirt) == 0x000F08, "Member 'ATrap_Ceiling_Falling_C::P_FallingDirt' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Tire_9) == 0x000F10, "Member 'ATrap_Ceiling_Falling_C::Tire_9' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Tire_8) == 0x000F18, "Member 'ATrap_Ceiling_Falling_C::Tire_8' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Tire_7) == 0x000F20, "Member 'ATrap_Ceiling_Falling_C::Tire_7' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Tire_6) == 0x000F28, "Member 'ATrap_Ceiling_Falling_C::Tire_6' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Tire_5) == 0x000F30, "Member 'ATrap_Ceiling_Falling_C::Tire_5' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Tire_4) == 0x000F38, "Member 'ATrap_Ceiling_Falling_C::Tire_4' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Tire_3) == 0x000F40, "Member 'ATrap_Ceiling_Falling_C::Tire_3' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Tire_2) == 0x000F48, "Member 'ATrap_Ceiling_Falling_C::Tire_2' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Tire_1) == 0x000F50, "Member 'ATrap_Ceiling_Falling_C::Tire_1' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, StaticMesh1) == 0x000F58, "Member 'ATrap_Ceiling_Falling_C::StaticMesh1' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Box) == 0x000F60, "Member 'ATrap_Ceiling_Falling_C::Box' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Root) == 0x000F68, "Member 'ATrap_Ceiling_Falling_C::Root' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, OpenDoor_Rotation_679D553A46783E44EDCECCA7D120A863) == 0x000F70, "Member 'ATrap_Ceiling_Falling_C::OpenDoor_Rotation_679D553A46783E44EDCECCA7D120A863' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, OpenDoor__Direction_679D553A46783E44EDCECCA7D120A863) == 0x000F74, "Member 'ATrap_Ceiling_Falling_C::OpenDoor__Direction_679D553A46783E44EDCECCA7D120A863' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, OpenDoor) == 0x000F78, "Member 'ATrap_Ceiling_Falling_C::OpenDoor' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, SocketTransforms) == 0x000F80, "Member 'ATrap_Ceiling_Falling_C::SocketTransforms' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, Tires) == 0x000F88, "Member 'ATrap_Ceiling_Falling_C::Tires' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, TimerHandle) == 0x000F98, "Member 'ATrap_Ceiling_Falling_C::TimerHandle' has a wrong offset!");
static_assert(offsetof(ATrap_Ceiling_Falling_C, bActivated) == 0x000FA0, "Member 'ATrap_Ceiling_Falling_C::bActivated' has a wrong offset!");

}

